"use strict";
const crypto=require("crypto");const bcrypt=require("bcrypt");const jwt=require("jsonwebtoken");const mongoose=require("mongoose");const Identidad=require("../models/identidadPersonal.model");const ResetToken=require("../models/resetTokenPersonal.model");const Suscripcion=require("../models/suscripcion.model");const {AUDIENCE,ISSUER,secret}=require("./personalToken.service");
const TTL="30m";
function sign(id){return jwt.sign({scope:"finanzas:personal",tokenVersion:id.tokenVersion},secret(),{algorithm:"HS256",subject:String(id._id),audience:AUDIENCE,issuer:ISSUER,expiresIn:TTL});}
async function registrar({email,nombre,password}){const normalized=email.trim().toLowerCase(),passwordHash=await bcrypt.hash(password,12),session=await mongoose.startSession();let id;try{await session.withTransaction(async()=>{const exists=await Identidad.exists({email:normalized}).session(session);if(exists)throw Object.assign(new Error("La cuenta ya existe"),{statusCode:409});[id]=await Identidad.create([{email:normalized,nombre,passwordHash}],{session});await Suscripcion.create([{userId:id._id,estado:"PRUEBA",vigenteHasta:new Date(Date.now()+14*86400000),proveedor:"GRUK_TRIAL"}],{session});},{readConcern:{level:"snapshot"},writeConcern:{w:"majority"},readPreference:"primary"});}catch(e){if(e?.code===11000)throw Object.assign(new Error("La cuenta ya existe"),{statusCode:409});throw e;}finally{await session.endSession();}return{token:sign(id),expiresInSeconds:1800,usuario:{id:id._id,nombre:id.nombre,email:id.email}};}
async function login({email,password}){const id=await Identidad.findOne({email:email.trim().toLowerCase()}).select("+passwordHash");const valid=id&&id.estado==="ACTIVA"&&await bcrypt.compare(password,id.passwordHash);if(!valid)throw Object.assign(new Error("Credenciales inválidas"),{statusCode:401});id.ultimoLoginEn=new Date();await id.save();return{token:sign(id),expiresInSeconds:1800,usuario:{id:id._id,nombre:id.nombre,email:id.email}};}
function resetHash(token){const s=process.env.PERSONAL_RESET_SECRET;if(!s)throw new Error("PERSONAL_RESET_SECRET requerido");return crypto.createHmac("sha256",s).update(token).digest("hex");}
async function solicitarReset(email){const id=await Identidad.findOne({email:String(email).trim().toLowerCase(),estado:"ACTIVA"}).lean();if(!id)return{accepted:true};const raw=crypto.randomBytes(32).toString("base64url"),session=await mongoose.startSession();try{await session.withTransaction(async()=>{await ResetToken.deleteMany({userId:id._id,usadoEn:null},{session});await ResetToken.create([{userId:id._id,tokenHash:resetHash(raw),expiraEn:new Date(Date.now()+15*60*1000)}],{session});});}finally{await session.endSession();}return{accepted:true,...(process.env.NODE_ENV==="test"?{deliveryToken:raw}:{})};}
async function confirmarReset({token,password}){const hash=resetHash(token),passwordHash=await bcrypt.hash(password,12),session=await mongoose.startSession();try{await session.withTransaction(async()=>{const doc=await ResetToken.findOneAndUpdate({tokenHash:hash,usadoEn:null,expiraEn:{$gt:new Date()}},{$set:{usadoEn:new Date()}},{new:true,session});if(!doc)throw Object.assign(new Error("Token inválido o expirado"),{statusCode:400});const id=await Identidad.findOneAndUpdate({_id:doc.userId,estado:"ACTIVA"},{$set:{passwordHash},$inc:{tokenVersion:1}},{new:true,session});if(!id)throw Object.assign(new Error("Token inválido o expirado"),{statusCode:400});},{readConcern:{level:"snapshot"},writeConcern:{w:"majority"},readPreference:"primary"});}finally{await session.endSession();}return{ok:true};}
module.exports={registrar,login,solicitarReset,confirmarReset};