"use strict";
const ledger=require("./resumenLedgerPersonal.service");const patrimonio=require("./patrimonioCanonico.service");const Prestamo=require("../models/prestamoPersonal.model");const home=require("./homePersonal.service");
function money(n){return new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(n);}
async function consultar(usuarioId,pregunta){const q=String(pregunta||"").trim().toLowerCase();if(!q)throw Object.assign(new Error("Pregunta requerida"),{statusCode:400});
 if(/cu[aá]nto.*(?:gastar|puedo)|disponible hoy|me alcanza/.test(q)){const h=await home.obtener(usuarioId);const a=h.asesor;if(!a.saldoRealMinor)return{tipo:"DISPONIBLE_HOY",respuesta:"Para decirte cuánto puedes gastar hoy necesito tu saldo real registrado. Sin ese número te estaría mintiendo.",datos:a};return{tipo:"DISPONIBLE_HOY",respuesta:a.estaEnRojo?"Hoy puedes gastar $0. Estás en rojo después de separar compromisos y el colchón del 10%.":"Hoy puedes gastar "+money(a.disponibleHoyMinor)+" sin tocar los compromisos registrados ni el colchón del 10%.",datos:a};}
 if(q.includes("patrimonio")){const p=await patrimonio.obtener(usuarioId);return{tipo:"PATRIMONIO",respuesta:"Tu patrimonio neto financiero registrado es "+money(p.patrimonioNetoMinor)+". Activos e inversiones suman "+money(p.activosMinor+p.inversionesMinor)+" y las deudas patrimoniales registradas suman "+money(p.deudasMinor)+".",datos:p,fuente:"patrimonio_canonico_v2"};}
 const r=await ledger.resumen(usuarioId);
 if(q.includes("deuda")||q.includes("credito")||q.includes("crédito")){const d=await Prestamo.find({usuarioId,direccion:"POR_PAGAR",estado:"ACTIVO"}).lean(),saldo=d.reduce((s,x)=>s+x.saldoMinor,0),cuotas=d.reduce((s,x)=>s+(x.cuotaMinor||0),0);return{tipo:"DEUDA",respuesta:"Tienes "+money(saldo)+" pendientes en deudas activas registradas y "+money(cuotas)+" en cuotas mensuales registradas.",datos:{saldoMinor:saldo,cuotasMinor:cuotas,deudas:d}};}
 if(q.includes("invert")){const h=await home.obtener(usuarioId),a=h.asesor;if(a.estaEnRojo||a.disponibleHoyMinor<=0)return{tipo:"INVERSION",respuesta:"Hoy no hay dinero libre registrado para invertir sin tocar compromisos y colchón. GRUK no va a inventarte capacidad de inversión.",datos:{...r,asesor:a}};return{tipo:"INVERSION",respuesta:"Tienes "+money(a.disponibleHoyMinor)+" disponibles después de compromisos y colchón. Para recomendar una inversión concreta todavía necesito horizonte, liquidez requerida y pérdida máxima que aceptarías; sin esos datos te estaría inventando el riesgo.",datos:{...r,asesor:a}};}
 return{tipo:"RESUMEN",respuesta:"Este mes: ingresos "+money(r.ingresosMinor)+", gastos "+money(r.gastosMinor)+", pagos de deuda "+money(r.pagosDeudaMinor)+" y flujo libre "+money(r.flujoLibreMinor)+".",datos:r};}
module.exports={consultar};
