"use strict";
const ledger=require("./resumenLedgerPersonal.service");const gastoInteligente=require("./gastoInteligentePersonal.service");const interprete=require("./interpreteFinanciero.service");const patrimonio=require("./patrimonioCanonico.service");const Prestamo=require("../models/prestamoPersonal.model");const home=require("./homePersonal.service");
function money(n){return new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(n);}
async function consultar(usuarioId,pregunta){const q=String(pregunta||"").trim().toLowerCase();if(!q)throw Object.assign(new Error("Pregunta requerida"),{statusCode:400});
 if(/cu[aá]nto.*(?:gastar|puedo)|disponible hoy|me alcanza/.test(q)){const h=await home.obtener(usuarioId);const a=h.asesor;if(!a.saldoRealConocido)return{tipo:"DISPONIBLE_HOY",respuesta:"Para decirte cuánto puedes gastar hoy necesito tu saldo real registrado. Sin ese número te estaría mintiendo.",datos:a};if(!a.proximoIngresoConocido)return{tipo:"DISPONIBLE_HOY",respuesta:"Tengo tu saldo real, pero no tengo registrada la fecha de tu próximo ingreso. Dime exactamente cuándo vuelves a recibir dinero; sin esa fecha no voy a fingir un Disponible Hoy exacto.",datos:a};const base=a.saldoRealMinor-a.gastosFijosAntesProximoIngresoMinor-a.colchonMinor,fecha=new Date(a.proximoIngreso.fecha).toLocaleDateString("es-CO",{timeZone:"America/Bogota",day:"2-digit",month:"2-digit",year:"numeric"});if(a.estaEnRojo){const faltante=Math.abs(base),consecuencia="Si gastas antes de cubrir ese faltante, reduces dinero reservado para obligaciones que vencen antes de tu próximo ingreso o para tu colchón; eso puede obligarte a aplazar un pago, usar deuda o quedarte sin liquidez. No significa que esas consecuencias ya hayan ocurrido.";return{tipo:"DISPONIBLE_HOY",respuesta:"Hoy puedes gastar $0. Cuenta: saldo registrado "+money(a.saldoRealMinor)+" − compromisos antes del "+fecha+" "+money(a.gastosFijosAntesProximoIngresoMinor)+" − colchón "+money(a.colchonMinor)+" = "+money(base)+". Te faltan "+money(faltante)+" para volver a $0 disponible. "+consecuencia+" Acción: no hagas gasto discrecional hasta cubrir "+money(faltante)+" o reprogramar un compromiso.",datos:{...a,faltanteMinor:faltante,consecuencia}};}return{tipo:"DISPONIBLE_HOY",respuesta:"Hoy puedes gastar "+money(a.disponibleHoyMinor)+". Cuenta: saldo registrado "+money(a.saldoRealMinor)+" − compromisos antes del "+fecha+" "+money(a.gastosFijosAntesProximoIngresoMinor)+" − colchón "+money(a.colchonMinor)+" = "+money(base)+". Si gastas más de "+money(a.disponibleHoyMinor)+", empezarías a usar dinero reservado para compromisos o colchón.",datos:{...a,consecuencia:"Superar el disponible consume protección destinada a compromisos o colchón."}};}
 if(/(?:me deben|por cobrar|quien me debe|quién me debe|plata pendiente)/.test(q)){const cs=await Prestamo.find({usuarioId,direccion:"POR_COBRAR",estado:{$in:["ACTIVO","VENCIDO"]},saldoMinor:{$gt:0}}).sort({fechaVencimiento:1}).lean();const total=cs.reduce((s,x)=>s+x.saldoMinor,0);return{tipo:"CUENTAS_POR_COBRAR",respuesta:cs.length?"Tienes "+money(total)+" pendientes por cobrar. Ese dinero no entra a Disponible Hoy hasta que realmente lo recibas.":"No tienes dinero pendiente por cobrar registrado.",datos:{cuentas:cs,totalMinor:total}};}
 if(/(?:puedo comprar|me conviene comprar|vale la pena|como gastar|cómo gastar|debo pagar|tengo que pagar)/.test(q)){const it=interprete.interpretarSegmento(pregunta),m=it&&it.montoMinor;if(!Number.isSafeInteger(m)||m<1)return{tipo:"GASTO_INTELIGENTE",respuesta:"Dime el precio exacto. Sin ese número no voy a inventar si te alcanza.",datos:{}};const obligatorio=/(?:debo pagar|tengo que pagar|arriendo|servicio|cuota|salud)/.test(q);const e=await gastoInteligente.evaluar(usuarioId,{montoMinor:m,obligatorio});return{tipo:"GASTO_INTELIGENTE",respuesta:e.mensaje,datos:e};}
 if(q.includes("patrimonio")){const p=await patrimonio.obtener(usuarioId);return{tipo:"PATRIMONIO",respuesta:"Tu patrimonio neto financiero registrado es "+money(p.patrimonioNetoMinor)+". Activos e inversiones suman "+money(p.activosMinor+p.inversionesMinor)+" y las deudas patrimoniales registradas suman "+money(p.deudasMinor)+".",datos:p,fuente:"patrimonio_canonico_v2"};}
 const r=await ledger.resumen(usuarioId);
 if(q.includes("deuda")||q.includes("credito")||q.includes("crédito")){const d=await Prestamo.find({usuarioId,direccion:"POR_PAGAR",estado:"ACTIVO"}).lean(),saldo=d.reduce((s,x)=>s+x.saldoMinor,0),cuotas=d.reduce((s,x)=>s+(x.cuotaMinor||0),0);return{tipo:"DEUDA",respuesta:"Tienes "+money(saldo)+" pendientes en deudas activas registradas y "+money(cuotas)+" en cuotas mensuales registradas.",datos:{saldoMinor:saldo,cuotasMinor:cuotas,deudas:d}};}
 if(q.includes("invert")){const h=await home.obtener(usuarioId),a=h.asesor;if(a.estaEnRojo||a.disponibleHoyMinor<=0)return{tipo:"INVERSION",respuesta:"Hoy no hay dinero libre registrado para invertir sin tocar compromisos y colchón. GRUK no va a inventarte capacidad de inversión.",datos:{...r,asesor:a}};return{tipo:"INVERSION",respuesta:"Tienes "+money(a.disponibleHoyMinor)+" disponibles después de compromisos y colchón. Para recomendar una inversión concreta todavía necesito horizonte, liquidez requerida y pérdida máxima que aceptarías; sin esos datos te estaría inventando el riesgo.",datos:{...r,asesor:a}};}
 return{tipo:"RESUMEN",respuesta:"Este mes: ingresos "+money(r.ingresosMinor)+", gastos "+money(r.gastosMinor)+", pagos de deuda "+money(r.pagosDeudaMinor)+" y flujo libre "+money(r.flujoLibreMinor)+".",datos:r};}
module.exports={consultar};
