"use strict";
const mongoose=require("mongoose");
const Movimiento=require("../models/movimiento.model");const Credito=require("../models/credito.model");const Perfil=require("../models/perfil.model");const Meta=require("../models/meta.model");
async function registrarMovimiento(userId,data){const session=await mongoose.startSession();try{let doc;await session.withTransaction(async()=>{[doc]=await Movimiento.create([{userId,...data}],{session});});return doc;}finally{await session.endSession();}}
async function diario(userId,{desde,hasta,limit=100}){const q={userId};if(desde||hasta){q.fecha={};if(desde)q.fecha.$gte=new Date(desde);if(hasta)q.fecha.$lte=new Date(hasta);}const movimientos=await Movimiento.find(q).sort({fecha:-1,createdAt:-1}).limit(Math.min(limit,500)).lean();const porDia={};for(const x of movimientos){const dia=new Date(x.fecha).toISOString().slice(0,10);porDia[dia]??={fecha:dia,ingresos:0,gastos:0,balance:0,movimientos:[]};porDia[dia][x.tipo==="INGRESO"?"ingresos":"gastos"]+=x.monto;porDia[dia].balance+=x.tipo==="INGRESO"?x.monto:-x.monto;porDia[dia].movimientos.push(x);}return Object.values(porDia).sort((a,b)=>b.fecha.localeCompare(a.fecha));}
async function resumenPeriodo(userId,{desde,hasta}){const q={userId,fecha:{$gte:new Date(desde),$lte:new Date(hasta)}};const m=await Movimiento.find(q).lean();const ingresos=m.filter(x=>x.tipo==="INGRESO").reduce((a,x)=>a+x.monto,0),gastos=m.filter(x=>x.tipo==="GASTO").reduce((a,x)=>a+x.monto,0);const categorias={};for(const x of m){const k=x.categoria;categorias[k]??={ingresos:0,gastos:0};categorias[k][x.tipo==="INGRESO"?"ingresos":"gastos"]+=x.monto;}return{desde,hasta,ingresos,gastos,balance:ingresos-gastos,categorias};}
async function upsertPerfil(userId,data){return Perfil.findOneAndUpdate({userId},{$set:data,$setOnInsert:{userId}},{new:true,upsert:true,runValidators:true});}
async function registrarCredito(userId,data){return Credito.create({userId,...data});}
async function crearMeta(userId,data){return Meta.create({userId,...data});}
async function resumen(userId){const [m,c,p,metas]=await Promise.all([Movimiento.find({userId}).lean(),Credito.find({userId,activo:true}).lean(),Perfil.findOne({userId}).lean(),Meta.find({userId,estado:"ACTIVA"}).lean()]);const ingresos=m.filter(x=>x.tipo==="INGRESO").reduce((a,x)=>a+x.monto,0);const gastos=m.filter(x=>x.tipo==="GASTO").reduce((a,x)=>a+x.monto,0);const deuda=c.reduce((a,x)=>a+x.saldo,0);const cuotas=c.reduce((a,x)=>a+x.cuotaMensual,0);const flujo=ingresos-gastos-cuotas;const carga=ingresos?cuotas/ingresos*100:0;const mesesFondo=gastos>0?Number(((p?.saldoLiquido||0)/(gastos/Math.max(1,new Set(m.map(x=>new Date(x.fecha).toISOString().slice(0,7))).size))).toFixed(2)):0;return{ingresos,gastos,cuotasDeuda:cuotas,flujoLibre:flujo,deudaTotal:deuda,cargaDeudaPct:Number(carga.toFixed(2)),tasaAhorroPct:ingresos?Number((flujo/ingresos*100).toFixed(2)):0,fondoEmergencia:{saldo:p?.saldoLiquido||0,mesesCubiertos:mesesFondo,objetivoMeses:p?.fondoEmergenciaObjetivoMeses||6},metasActivas:metas.map(x=>({id:x._id,nombre:x.nombre,objetivo:x.objetivo,acumulado:x.acumulado,progresoPct:x.objetivo?Number((x.acumulado/x.objetivo*100).toFixed(2)):0}))};}
function simularCredito({capital,tasaMensualPct,meses}){const r=tasaMensualPct/100;const cuota=r===0?capital/meses:capital*(r*Math.pow(1+r,meses))/(Math.pow(1+r,meses)-1);const total=cuota*meses;const tea=(Math.pow(1+r,12)-1)*100;return{cuotaMensual:Number(cuota.toFixed(2)),costoTotal:Number(total.toFixed(2)),interesesEstimados:Number((total-capital).toFixed(2)),tasaMensualPct,tasaEfectivaAnualPct:Number(tea.toFixed(2)),meses};}
async function evaluarCredito(userId,input){const base=await resumen(userId);const simulacion=simularCredito(input);const flujoPosterior=base.flujoLibre-simulacion.cuotaMensual;const cargaPosterior=base.ingresos?((base.cuotasDeuda+simulacion.cuotaMensual)/base.ingresos)*100:null;return{simulacion,contexto:{ingresosRegistrados:base.ingresos,flujoLibreActual:base.flujoLibre,flujoLibrePosterior:Number(flujoPosterior.toFixed(2)),cargaDeudaPosteriorPct:cargaPosterior===null?null:Number(cargaPosterior.toFixed(2))},alertas:[...(flujoPosterior<0?["La cuota proyectada llevaría el flujo libre registrado a terreno negativo."]:[]),...(cargaPosterior!==null&&cargaPosterior>35?["La carga mensual de deuda proyectada supera el 35% de los ingresos registrados."]:[])],supuestos:"Cálculo determinístico con los datos registrados; no incluye seguros, comisiones, impuestos ni cambios futuros salvo que se incorporen al escenario."};}
module.exports={registrarMovimiento,diario,resumenPeriodo,upsertPerfil,registrarCredito,crearMeta,resumen,simularCredito,evaluarCredito};