"use strict";
const Macro=require("../models/macroSnapshot.model");
const SOURCES={inflacion:"https://www.dane.gov.co/index.php/estadisticas-por-tema/precios-y-costos/indice-de-precios-al-consumidor-ipc/ipc-informacion-tecnica",ibr:"https://www.banrep.gov.co/es/glosario/indicador-bancario-referencia-ibr"};
async function html(url){const r=await fetch(url,{headers:{"user-agent":"GRUK-MacroCollector/1.1","accept":"text/html"},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error("Fuente oficial HTTP "+r.status);return r.text()}
function normalized(s){return s.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/\s+/g," ").trim()}
function decimal(s){const n=Number(String(s).replace(",","."));if(!Number.isFinite(n))throw new Error("NO_CALCULABLE: valor oficial inválido");return n}
function parseDane(raw){const t=normalized(raw),m=t.match(/En\s+([A-Za-záéíóúñ]+)\s+de\s+(20\d{2})[\s\S]{0,350}?variaci[oó]n\s+anual(?:\s+del\s+IPC)?\s+(?:fue|se\s+ubic[oó]\s+en)\s+([0-9]+[,.][0-9]+)%/i);if(!m)throw new Error("NO_CALCULABLE: DANE sin IPC anual verificable");return{value:decimal(m[3]),period:m[1]+" "+m[2]}}
function parseIbr(raw){const t=normalized(raw),m=t.match(/Indicador bancario de referencia \(IBR\) Overnight[\s\S]{0,300}?Tasa nominal[\s\S]{0,120}?([0-9]+[,.][0-9]+)%[\s\S]{0,120}?(\d{2}\/\d{2}\/20\d{2})/i);if(!m)throw new Error("NO_CALCULABLE: BanRep sin IBR Overnight verificable");return{value:decimal(m[1]),period:m[2]}}
async function collectColombia(){const [daneRaw,ibrRaw]=await Promise.all([html(SOURCES.inflacion),html(SOURCES.ibr)]),dane=parseDane(daneRaw),ibr=parseIbr(ibrRaw);if(dane.value<0||dane.value>100||ibr.value<0||ibr.value>100)throw new Error("NO_CALCULABLE: macro fuera de rango");return{pais:"CO",moneda:"COP",fechaCorte:new Date(),inflacionAnualPct:dane.value,tasaLibreRiesgoPct:ibr.value,fuenteInflacion:SOURCES.inflacion,fuenteTasa:SOURCES.ibr,metodologiaTasa:"Proxy monetario COP: IBR Overnight nominal observado ("+ibr.period+"). IPC anual DANE: "+dane.period+". El IBR es referencia interbancaria de corto plazo y no equivale a un rendimiento soberano libre de riesgo a 5 años."}}
async function persistColombia(){const x=await collectColombia();return Macro.create(x)}
module.exports={collectColombia,persistColombia,parseDane,parseIbr,SOURCES};