"use strict";
const express=require("express"),Joi=require("joi");
const tarjetaCredito=require("./services/tarjetaCreditoPersonal.service");const validate=schema=>(req,res,next)=>{const {value,error}=schema.validate(req.body,{abortEarly:false,stripUnknown:true});if(error)return res.status(400).json({ok:false,error:"Datos inválidos",detalles:error.details.map(x=>x.message)});req.validated=value;return next();};const auth=require("./security/personalAuth.middleware"),entitlement=require("./security/entitlement.middleware"),service=require("./services/finanzasPersonales.service"),flujoCaja=require("./services/flujoCajaPersonal.service"),brain=require("./intelligence/brain"),consulta=require("./services/consultaPersonal.service"),cerebroPersonal=require("./intelligence/personal_brain/cerebro_personal"),migracionLedger=require("./services/migracionLedgerPersonal.service");const patrimonioV2=require("./routesPatrimonioV2");const personalAuthService=require("./security/personalAuth.service");const patrimonioPersonal=require("./services/patrimonioPersonal.service");const personalAuthRateLimit=require("./security/personalAuthRateLimit.middleware");const interpreteFinanciero=require("./services/interpreteFinanciero.service");const aprobacionConversacional=require("./services/aprobacionConversacional.service");const BorradorFinanciero=require("./models/borradorFinanciero.model");const investmentIntelligence=require("./services/investmentIntelligence.service");const homePersonal=require("./services/homePersonal.service");const conversacionPersonal=require("./services/conversacionPersonal.service");const RecomendacionInversion=require("./models/recomendacionInversion.model");const mentorAdaptativo=require("./services/mentorAdaptativo.service");const progresoEconomico=require("./services/progresoEconomicoPersonal.service");const obligacionesPersonal=require("./services/obligacionesPersonal.service");const router=express.Router();const authLimiter=personalAuthRateLimit({windowMs:15*60*1000,max:8});
const registroSchema=Joi.object({email:Joi.string().email().max(254).required(),nombre:Joi.string().trim().min(2).max(120).required(),password:Joi.string().min(12).max(128).required()});
const loginSchema=Joi.object({email:Joi.string().email().max(254).required(),password:Joi.string().min(12).max(128).required(),mantenerSesion:Joi.boolean().default(false)});
router.post("/auth/registro",authLimiter,validate(registroSchema),async(req,res)=>{try{return res.status(201).json({ok:true,...await personalAuthService.registrar(req.validated)});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"Error interno"});}});
router.post("/auth/login",authLimiter,validate(loginSchema),async(req,res)=>{try{return res.json({ok:true,...await personalAuthService.login(req.validated)});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"Error interno"});}});
router.use(auth,entitlement);router.use(patrimonioV2);const accionProgresoSchema=Joi.object({estado:Joi.string().valid("APROBADA","COMPLETADA","DESCARTADA").required(),resultadoMinor:Joi.number().integer().min(0).max(Number.MAX_SAFE_INTEGER),evidencia:Joi.string().trim().max(300).allow(""),transaccionEvidenciaId:Joi.string().hex().length(24)});
router.patch("/progreso-economico/acciones/:id",validate(accionProgresoSchema),async(req,res)=>{
 if(!/^[a-f0-9]{24}$/i.test(req.params.id))return res.status(400).json({ok:false,error:"Identificador inválido"});
 const mongoose=require("mongoose"),crypto=require("crypto"),A=require("./models/accionProgresoPersonal.model"),Tx=require("./models/TransaccionPersonal"),Outbox=require("./models/outboxPersonal.model"),session=await mongoose.startSession();let salida;
 try{await session.withTransaction(async()=>{const actual=await A.findOne({_id:req.params.id,usuarioId:req.personalAuth.userId}).session(session);if(!actual)throw Object.assign(new Error("Acción no encontrada"),{statusCode:404});const anterior=actual.estado,siguiente=req.validated.estado,permitidas={PROPUESTA:["APROBADA","DESCARTADA"],APROBADA:["COMPLETADA","DESCARTADA"],COMPLETADA:[],DESCARTADA:[]};if(!permitidas[anterior].includes(siguiente))throw Object.assign(new Error("Transición de acción no permitida"),{statusCode:409});if(siguiente==="COMPLETADA"){if(req.validated.resultadoMinor===undefined||!req.validated.transaccionEvidenciaId)throw Object.assign(new Error("Para completar debes registrar resultado y movimiento financiero de respaldo"),{statusCode:422});const tx=await Tx.findOne({_id:req.validated.transaccionEvidenciaId,usuarioId:req.personalAuth.userId,estado:{$ne:"ANULADA"}}).session(session).lean();if(!tx)throw Object.assign(new Error("La evidencia contable no existe o fue anulada"),{statusCode:422});const tipos={INGRESOS:["INGRESO"],COBRO:["COBRO_PRESTAMO"],GASTO:["GASTO"],DEUDA:["PAGO_DEUDA"]};if(!(tipos[actual.palanca]||[]).includes(tx.tipo))throw Object.assign(new Error("El movimiento no corresponde a la palanca económica de la acción"),{statusCode:422});if(req.validated.resultadoMinor>tx.montoMinor)throw Object.assign(new Error("El resultado declarado supera el movimiento que lo respalda"),{statusCode:422});actual.transaccionEvidenciaId=tx._id;}actual.estado=siguiente;if(req.validated.resultadoMinor!==undefined)actual.resultadoMinor=req.validated.resultadoMinor;if(req.validated.evidencia!==undefined)actual.evidencia=req.validated.evidencia;if(siguiente==="COMPLETADA")actual.completadaEn=new Date();await actual.save({session});await Outbox.create([{usuarioId:req.personalAuth.userId,eventId:crypto.randomUUID(),eventName:"ACCION_PROGRESO_ACTUALIZADA",aggregateType:"ACCION_PROGRESO_PERSONAL",aggregateId:actual._id,payload:{accionId:String(actual._id),estadoAnterior:anterior,estadoNuevo:siguiente,palanca:actual.palanca,objetivoMinor:actual.objetivoMinor,resultadoMinor:actual.resultadoMinor,transaccionEvidenciaId:actual.transaccionEvidenciaId?String(actual.transaccionEvidenciaId):null}}],{session});salida=actual.toObject();},{readConcern:{level:"snapshot"},writeConcern:{w:"majority"},readPreference:"primary"});return res.json({ok:true,accion:salida,medicion:salida.estado==="COMPLETADA"?{baselineMinor:salida.baselineMinor,objetivoMinor:salida.objetivoMinor,resultadoMinor:salida.resultadoMinor,cumplimientoObjetivo:salida.objetivoMinor>0?salida.resultadoMinor>=salida.objetivoMinor:null}:null});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"No fue posible actualizar la acción económica"});}finally{await session.endSession();}
});
router.get("/progreso-economico",async(req,res)=>{try{return res.json({ok:true,progreso:await progresoEconomico.analizar(req.personalAuth.userId)});}catch(e){console.error("[FIN_PERSONAL_PROGRESO]",e);return res.status(500).json({ok:false,error:"No fue posible medir el progreso económico"});}});
const obligacionSchema=Joi.object({montoMinor:Joi.number().integer().min(1).required(),concepto:Joi.string().trim().max(140).allow("").default(""),costoRenegociarMinor:Joi.number().integer().min(0),consecuenciaRenegociar:Joi.string().trim().max(240).allow(""),costoReprogramarMinor:Joi.number().integer().min(0),consecuenciaReprogramar:Joi.string().trim().max(240).allow(""),costoSustituirMinor:Joi.number().integer().min(0),consecuenciaSustituir:Joi.string().trim().max(240).allow("")});router.post("/obligaciones/evaluar",validate(obligacionSchema),async(req,res)=>{try{return res.json({ok:true,evaluacion:await obligacionesPersonal.evaluar(req.personalAuth.userId,req.validated)});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"No fue posible evaluar la obligación"});}});
router.get("/notificaciones",async(req,res)=>{const N=require("./models/notificacionPersonal.model");const rows=await N.find({usuarioId:req.personalAuth.userId,leidaEn:null}).sort({createdAt:-1}).limit(50).lean();return res.json({ok:true,notificaciones:rows});});router.post("/notificaciones/:id/leida",async(req,res)=>{if(!/^[a-f0-9]{24}$/i.test(req.params.id))return res.status(400).json({ok:false,error:"Identificador inválido"});const N=require("./models/notificacionPersonal.model");const n=await N.findOneAndUpdate({_id:req.params.id,usuarioId:req.personalAuth.userId},{$set:{leidaEn:new Date()}},{new:true});return n?res.json({ok:true}):res.status(404).json({ok:false,error:"Notificación no encontrada"});});
router.get("/home",async(req,res)=>{try{return res.json({ok:true,home:await homePersonal.obtener(req.personalAuth.userId)});}catch(e){console.error("[FIN_PERSONAL_HOME]",e);return res.status(500).json({ok:false,error:"No fue posible construir el estado financiero personal"});}});
const cuentaSchema=Joi.object({nombre:Joi.string().trim().min(1).max(100).required(),tipo:Joi.string().valid("EFECTIVO","AHORROS","CORRIENTE","BILLETERA","INVERSION","OTRA").required(),institucion:Joi.string().trim().max(120).allow("").default(""),moneda:Joi.string().valid("COP").default("COP"),saldoMinor:Joi.number().integer().min(0).default(0),saldoVerificado:Joi.boolean().default(false)});
router.post("/cuentas",validate(cuentaSchema),async(req,res)=>{try{return res.status(201).json({ok:true,cuenta:await patrimonioPersonal.crearCuenta(req.personalAuth.userId,{...req.validated,saldoVerificadoEn:req.validated.saldoVerificado?new Date():null,origenSaldo:req.validated.saldoVerificado?"USUARIO":"NO_VERIFICADO",requiereReconciliacion:!req.validated.saldoVerificado})});}catch(e){return res.status(e.code===11000?409:e.statusCode||500).json({ok:false,error:e.code===11000?"Ya existe una cuenta con ese nombre":e.statusCode?e.message:"Error interno"});}});
router.get("/patrimonio-financiero",async(req,res)=>res.json({ok:true,snapshot:await patrimonioPersonal.snapshot(req.personalAuth.userId)}));
router.post("/prestamos/reparar-moto",async(req,res)=>{const mongoose=require("mongoose"),crypto=require("crypto"),Prestamo=require("./models/prestamoPersonal.model"),Tx=require("./models/TransaccionPersonal"),Outbox=require("./models/outboxPersonal.model");const session=await mongoose.startSession();try{let repaired=false,anulados=0;await session.withTransaction(async()=>{const candidates=await Prestamo.find({usuarioId:req.personalAuth.userId,direccion:"POR_PAGAR",estado:{$in:["ACTIVO","VENCIDO"]},concepto:/moto/i}).session(session);if(candidates.length!==1)throw Object.assign(new Error(candidates.length?"Reparación cancelada: hay más de una deuda de moto activa":"No encontré la deuda de moto a reparar"),{statusCode:409});const p=candidates[0];const canonical=p.principalMinor===7000000&&p.saldoMinor===4500000&&p.cuotaMinor===1000000&&p.tasaMensualPct===0;if(!canonical){const corrupt=(p.saldoMinor===0&&p.cuotaMinor===15)||(/imag[ií]nate|compr[eé].*moto/i.test(p.concepto)&&p.saldoMinor===0);if(!corrupt)throw Object.assign(new Error("La deuda encontrada no coincide con el patrón reparable; no se modificó"),{statusCode:409});p.concepto="Moto";p.contraparte=p.contraparte||"Por identificar";p.principalMinor=7000000;p.saldoMinor=4500000;p.cuotaMinor=1000000;p.tasaMensualPct=0;repaired=true}const now=new Date(),day=15;let y=now.getFullYear(),m=now.getMonth();if(now.getDate()>day){m++;if(m>11){m=0;y++}}p.fechaVencimiento=new Date(y,m,day,12,0,0,0);await p.save({session});const bad=await Tx.find({usuarioId:req.personalAuth.userId,tipo:"GASTO",montoMinor:7000000,estado:{$ne:"ANULADA"},$or:[{concepto:/moto/i},{descripcion:/moto/i}]}).session(session);for(const tx of bad){tx.estado="ANULADA";tx.anuladaEn=new Date();tx.motivoAnulacion="RECONCILIACION_DEUDA_PRINCIPAL_MOTO";await tx.save({session});await Outbox.create([{usuarioId:req.personalAuth.userId,eventId:crypto.randomUUID(),eventName:"MOVIMIENTO_PATRIMONIAL",aggregateId:tx._id,payload:{transaccionId:String(tx._id),accion:"ANULACION_ASIENTO_PRINCIPAL_DEUDA",montoMinor:tx.montoMinor,prestamoId:String(p._id)}}],{session});anulados++}},{readConcern:{level:"snapshot"},writeConcern:{w:"majority"},readPreference:"primary"});return res.json({ok:true,repaired,anulados});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"Reparación no completada"});}finally{await session.endSession()}});
router.get("/prestamos",async(req,res)=>{const Prestamo=require("./models/prestamoPersonal.model");const prestamos=await Prestamo.find({usuarioId:req.personalAuth.userId}).sort({estado:1,fechaVencimiento:1,createdAt:-1}).lean();return res.json({ok:true,prestamos});});
const prestamoSchema=Joi.object({direccion:Joi.string().valid("POR_COBRAR","POR_PAGAR").required(),contraparte:Joi.string().trim().max(140).required(),concepto:Joi.string().trim().max(160).default("Préstamo"),principalMinor:Joi.number().integer().min(1).required(),tasaMensualPct:Joi.number().min(0).max(100).default(0),cuotaMinor:Joi.number().integer().min(0).default(0),fechaInicio:Joi.date().iso().required(),fechaVencimiento:Joi.date().iso().allow(null),cuentaId:Joi.string().hex().length(24).allow(null)});
router.post("/prestamos",validate(prestamoSchema),async(req,res)=>{try{return res.status(201).json({ok:true,prestamo:await patrimonioPersonal.crearPrestamo(req.personalAuth.userId,req.validated)});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"Error interno"});}});
const transferenciaSchema=Joi.object({origenId:Joi.string().hex().length(24).required(),destinoId:Joi.string().hex().length(24).required(),montoMinor:Joi.number().integer().min(1).required()});
router.post("/transferencias",validate(transferenciaSchema),async(req,res)=>{try{return res.json({ok:true,transferencia:await patrimonioPersonal.transferir(req.personalAuth.userId,req.validated)});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"Error interno"});}});

const inversionAnalisisSchema=Joi.object({capitalMinor:Joi.number().integer().min(1).max(Number.MAX_SAFE_INTEGER).required(),perfilRiesgo:Joi.string().valid("CONSERVADOR","MODERADO","AGRESIVO"),horizonteMeses:Joi.number().integer().min(1).max(600),drawdownMaxPct:Joi.number().min(0).max(100).required(),liquidezMaxDias:Joi.number().integer().min(0).max(3650).required()});
router.post("/inversiones/inteligencia",validate(inversionAnalisisSchema),async(req,res)=>{try{return res.json({ok:true,recomendacion:await investmentIntelligence.analizar(req.personalAuth.userId,req.validated)});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"Error interno"});}});
const mentorFeedbackSchema=Joi.object({decisionId:Joi.string().max(120).required(),rubro:Joi.string().max(80).default("GENERAL"),accion:Joi.string().valid("ACEPTADA","RECHAZADA").required(),motivo:Joi.string().allow("").max(240).default("")});router.post("/mentor/feedback",validate(mentorFeedbackSchema),async(req,res)=>{try{return res.json({ok:true,preferencias:await mentorAdaptativo.registrar(req.personalAuth.userId,req.validated)});}catch(e){if(e?.code===11000)return res.status(409).json({ok:false,error:"Esta decisión ya recibió feedback"});throw e}});
router.get("/inversiones/inteligencia/ultima",async(req,res)=>{const r=await RecomendacionInversion.findOne({usuarioId:req.personalAuth.userId}).sort({timestamp:-1}).lean();return res.json({ok:true,recomendacion:r});});

const capturaSchema=Joi.object({texto:Joi.string().trim().min(2).max(5000).required(),canal:Joi.string().valid("TEXTO","AUDIO_TRANSCRITO").default("TEXTO")});
router.post("/copilot",validate(capturaSchema),async(req,res)=>{try{return res.json({ok:true,resultado:await conversacionPersonal.procesar(req.personalAuth.userId,req.validated)});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"Error interno"});}});
router.post("/captura/interpretar",validate(capturaSchema),async(req,res)=>{try{return res.status(201).json({ok:true,borrador:await interpreteFinanciero.crearBorrador(req.personalAuth.userId,req.validated)});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"Error interno"});}});
router.get("/captura/pendientes",async(req,res)=>res.json({ok:true,borradores:await BorradorFinanciero.find({usuarioId:req.personalAuth.userId,estado:{$in:["PENDIENTE","PARCIAL"]}}).sort({createdAt:-1}).limit(50).lean()}));
router.post("/captura/:id/aprobar",async(req,res)=>{if(!/^[a-f0-9]{24}$/i.test(req.params.id))return res.status(400).json({ok:false,error:"Identificador inválido"});try{return res.json({ok:true,resultado:await aprobacionConversacional.aprobar(req.personalAuth.userId,req.params.id)});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"Error interno"});}});router.post("/captura/:id/items/:itemId/aprobar",async(req,res)=>{if(!/^[a-f0-9]{24}$/i.test(req.params.id)||!/^[a-f0-9]{24}$/i.test(req.params.itemId))return res.status(400).json({ok:false,error:"Identificador inválido"});try{return res.json({ok:true,resultado:await aprobacionConversacional.aprobar(req.personalAuth.userId,req.params.id,req.params.itemId)});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"Error interno"});}});
router.post("/captura/:id/descartar",async(req,res)=>{if(!/^[a-f0-9]{24}$/i.test(req.params.id))return res.status(400).json({ok:false,error:"Identificador inválido"});const b=await BorradorFinanciero.findOneAndUpdate({_id:req.params.id,usuarioId:req.personalAuth.userId,estado:"PENDIENTE"},{$set:{estado:"DESCARTADO"}},{new:true});return b?res.json({ok:true}):res.status(404).json({ok:false,error:"Borrador no disponible"});});

router.post("/migracion/ledger",async(req,res)=>{try{return res.json({ok:true,reporte:await migracionLedger.migrar(req.personalAuth.userId)});}catch(e){console.error("[FIN_PERSONAL_MIGRACION]",e);return res.status(500).json({ok:false,error:"Migración no completada; datos legacy preservados"});}});
router.get("/migracion/reconciliacion",async(req,res)=>{try{return res.json({ok:true,reporte:await migracionLedger.reconciliar(req.personalAuth.userId)});}catch(e){return res.status(500).json({ok:false,error:"No fue posible reconciliar"});}});
const pregunta=Joi.object({pregunta:Joi.string().trim().min(2).max(500).required()});
router.post("/consulta",validate(pregunta),async(req,res)=>res.json({ok:true,resultado:await consulta.consultar(req.personalAuth.userId,req.validated.pregunta)}));
const decisionInput=Joi.object({desde:Joi.date().iso().required(),hasta:Joi.date().iso().required(),objetivoAhorroPct:Joi.number().min(0).max(100).default(20),ingresoMensual:Joi.number().min(0).default(0),pagoExtraDisponible:Joi.number().min(0).default(0),umbralCargaPct:Joi.number().min(0).max(100).default(35)});
router.post("/cerebro/decidir",validate(decisionInput),async(req,res)=>res.json({ok:true,decision:await cerebroPersonal.tomarDecisionPersonal(req.personalAuth.userId,req.validated)}));

const transaccion=Joi.object({prestamoId:Joi.string().hex().length(24).allow(null),tipo:Joi.string().valid("INGRESO","GASTO","PAGO_DEUDA","PRESTAMO_OTORGADO","PRESTAMO_RECIBIDO","COBRO_PRESTAMO").required(),montoMinor:Joi.number().integer().min(1).max(Number.MAX_SAFE_INTEGER).required(),moneda:Joi.string().valid("COP").default("COP"),concepto:Joi.string().trim().max(140).required(),categoria:Joi.string().trim().max(80).required(),subcategoria:Joi.string().trim().max(80).allow("").default(""),cuenta:Joi.string().trim().max(100).default("EFECTIVO"),medioPago:Joi.string().valid("EFECTIVO","DEBITO","CREDITO","TRANSFERENCIA","PSE","OTRO").default("EFECTIVO"),contraparte:Joi.string().trim().max(140).allow("").default(""),descripcion:Joi.string().trim().max(240).allow("").default(""),recurrente:Joi.boolean().default(false),frecuencia:Joi.string().valid("NINGUNA","DIARIA","SEMANAL","QUINCENAL","MENSUAL","ANUAL").default("NINGUNA"),fecha:Joi.date().iso().required(),origen:Joi.string().valid("MANUAL","OPEN_BANKING","PASARELA","COMPROBANTE","SISTEMA").default("MANUAL"),externalId:Joi.string().max(160),metadatosSensibles:Joi.object().unknown(true)});
const tarjetaOperacion=Joi.object({deudaId:Joi.string().hex().length(24).required(),montoMinor:Joi.number().integer().min(1).max(Number.MAX_SAFE_INTEGER).required(),concepto:Joi.string().trim().max(140),categoria:Joi.string().trim().max(80),cuenta:Joi.string().trim().max(100),fecha:Joi.date().iso()});router.post("/tarjetas/compras",validate(tarjetaOperacion),async(req,res)=>{try{return res.status(201).json({ok:true,transaccion:await tarjetaCredito.comprar(req.personalAuth.userId,req.validated)});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"No fue posible registrar la compra con tarjeta"});}});router.post("/tarjetas/pagos",validate(tarjetaOperacion),async(req,res)=>{try{return res.status(201).json({ok:true,transaccion:await tarjetaCredito.pagar(req.personalAuth.userId,req.validated)});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"No fue posible pagar la tarjeta"});}});router.post("/transacciones",validate(transaccion),async(req,res)=>{try{return res.status(201).json({ok:true,transaccion:await flujoCaja.registrarTransaccion(req.personalAuth.userId,req.validated)});}catch(e){if(e?.code===11000)return res.status(409).json({ok:false,error:"Transacción duplicada"});return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"Error interno"});}});
const correccionTx=Joi.object({tipo:Joi.string().valid("INGRESO","GASTO"),montoMinor:Joi.number().integer().min(1).max(Number.MAX_SAFE_INTEGER),concepto:Joi.string().trim().max(140),categoria:Joi.string().trim().max(80)}).min(1);
router.patch("/transacciones/:id",validate(correccionTx),async(req,res)=>{try{const tx=await flujoCaja.corregirTransaccion(req.personalAuth.userId,req.params.id,req.validated);return tx?res.json({ok:true,transaccion:tx}):res.status(404).json({ok:false,error:"Movimiento no encontrado"});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"No fue posible corregir el movimiento"});}});
router.delete("/transacciones/:id",async(req,res)=>{try{return res.json({ok:true,transaccion:await flujoCaja.anularTransaccion(req.personalAuth.userId,req.params.id,"Eliminada manualmente por el usuario")});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"No fue posible eliminar el movimiento"});}});
router.get("/flujo-caja",async(req,res)=>{try{const desde=req.query.desde,hasta=req.query.hasta;if(!desde||!hasta)return res.status(400).json({ok:false,error:"desde y hasta son obligatorios"});return res.json({ok:true,flujo:await flujoCaja.flujoPeriodo(req.personalAuth.userId,{desde,hasta})});}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"Error interno"});}});
const movimiento=Joi.object({tipo:Joi.string().valid("INGRESO","GASTO").required(),monto:Joi.number().integer().positive().max(Number.MAX_SAFE_INTEGER).required(),concepto:Joi.string().max(140).required(),categoria:Joi.string().max(80).required(),subcategoria:Joi.string().max(80).allow("").default(""),cuenta:Joi.string().max(100).default("EFECTIVO"),medioPago:Joi.string().valid("EFECTIVO","DEBITO","CREDITO","TRANSFERENCIA","PSE","OTRO").default("EFECTIVO"),contraparte:Joi.string().max(140).allow("").default(""),descripcion:Joi.string().max(240).allow("").default(""),fecha:Joi.date().iso().required(),recurrente:Joi.boolean().default(false),frecuencia:Joi.string().valid("NINGUNA","DIARIA","SEMANAL","QUINCENAL","MENSUAL","ANUAL").default("NINGUNA"),origen:Joi.string().valid("MANUAL","IMPORTADO","WEBHOOK").default("MANUAL"),externalId:Joi.string().max(160).allow(null)});
router.post("/movimientos",validate(movimiento),async(req,res)=>{try{const d=req.validated;const tx=await flujoCaja.registrarTransaccion(req.personalAuth.userId,{tipo:d.tipo,montoMinor:d.monto,moneda:"COP",concepto:d.concepto,categoria:d.categoria,subcategoria:d.subcategoria,cuenta:d.cuenta,medioPago:d.medioPago,contraparte:d.contraparte,descripcion:d.descripcion,recurrente:d.recurrente,frecuencia:d.frecuencia,fecha:d.fecha,origen:d.origen==="WEBHOOK"?"PASARELA":d.origen==="IMPORTADO"?"SISTEMA":"MANUAL",externalId:d.externalId||undefined});return res.status(201).json({ok:true,movimiento:tx,fuente:"ledger_canonico"});}catch(e){if(e?.code===11000)return res.status(409).json({ok:false,error:"Movimiento duplicado"});console.error("[FIN_PERSONAL]",e);return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"Error interno"});}});
router.get("/diario",async(req,res)=>{try{const limit=Math.min(Number(req.query.limit)||100,500);return res.json({ok:true,dias:await service.diario(req.personalAuth.userId,{desde:req.query.desde,hasta:req.query.hasta,limit})});}catch(e){console.error("[FIN_PERSONAL_DIARIO]",e);return res.status(500).json({ok:false,error:"Error interno"});}});
router.get("/resumen-periodo",async(req,res)=>{try{const desde=req.query.desde,hasta=req.query.hasta;if(!desde||!hasta)return res.status(400).json({ok:false,error:"desde y hasta son obligatorios"});return res.json({ok:true,resumen:await service.resumenPeriodo(req.personalAuth.userId,{desde,hasta})});}catch(e){console.error("[FIN_PERSONAL_PERIODO]",e);return res.status(500).json({ok:false,error:"Error interno"});}});
const perfil=Joi.object({moneda:Joi.string().length(3),fondoEmergenciaObjetivoMeses:Joi.number().integer().min(1).max(24),ahorroObjetivoPct:Joi.number().min(0).max(100),saldoLiquido:Joi.number().integer().min(0).max(Number.MAX_SAFE_INTEGER)}).min(1);
router.put("/perfil",validate(perfil),async(req,res)=>res.json({ok:true,perfil:await service.upsertPerfil(req.personalAuth.userId,req.validated)}));
const activo=Joi.object({nombre:Joi.string().max(120).required(),tipo:Joi.string().valid("EFECTIVO","CUENTA","INVERSION","INMUEBLE","VEHICULO","OTRO").required(),valorActual:Joi.number().integer().min(0).max(Number.MAX_SAFE_INTEGER).required(),liquido:Joi.boolean().default(false),institucion:Joi.string().max(120).allow("").default("")});
router.post("/activos",validate(activo),async(req,res)=>res.status(201).json({ok:true,activo:await service.registrarActivo(req.personalAuth.userId,req.validated)}));
router.post("/activos/reconciliar-moto",async(req,res)=>{try{
 const ActivoPatrimonial=require("./models/ActivoPatrimonial"),Prestamo=require("./models/prestamoPersonal.model");
 const deuda=await Prestamo.findOne({usuarioId:req.personalAuth.userId,direccion:"POR_PAGAR",estado:{$in:["ACTIVO","VENCIDO"]},concepto:/moto/i}).lean();
 if(!deuda)return res.status(404).json({ok:false,error:"No existe una deuda activa de moto para reconciliar"});
 const existente=await ActivoPatrimonial.findOne({usuarioId:req.personalAuth.userId,tipo:"VEHICULO",nombre:/moto/i});
 if(existente)return res.json({ok:true,activo:existente,reconciliado:false});
 const principal=Number(deuda.principalMinor||0);
 if(!Number.isSafeInteger(principal)||principal<=0)return res.status(409).json({ok:false,error:"La deuda no tiene principal válido para sustentar el valor registrado"});
 const activo=await ActivoPatrimonial.create({usuarioId:req.personalAuth.userId,nombre:"Moto",tipo:"VEHICULO",valorMinor:principal,moneda:"COP",liquido:false,institucion:"Valor registrado al costo de adquisición"});
 return res.status(201).json({ok:true,activo,reconciliado:true});
 }catch(e){console.error("[RECONCILIAR_MOTO]",e);return res.status(500).json({ok:false,error:"No fue posible reconciliar el activo"});}});

const inversion=Joi.object({nombre:Joi.string().max(140).required(),clase:Joi.string().valid("EFECTIVO_RENTABLE","RENTA_FIJA","RENTA_VARIABLE","FONDO","ETF","CRIPTO","INMOBILIARIA","OTRA").required(),capitalAportado:Joi.number().integer().min(0).max(Number.MAX_SAFE_INTEGER).required(),valorActual:Joi.number().integer().min(0).max(Number.MAX_SAFE_INTEGER).required(),moneda:Joi.string().length(3).default("COP"),liquidezDias:Joi.number().integer().min(0).allow(null),riesgoDeclarado:Joi.string().valid("BAJO","MEDIO","ALTO","NO_CLASIFICADO").default("NO_CLASIFICADO"),institucion:Joi.string().max(120).allow("").default("")});
router.post("/inversiones",validate(inversion),async(req,res)=>res.status(201).json({ok:true,inversion:await service.registrarInversion(req.personalAuth.userId,req.validated)}));
const perfilInv=Joi.object({horizonteMeses:Joi.number().integer().min(1).max(600).required(),toleranciaRiesgo:Joi.string().valid("CONSERVADOR","MODERADO","AGRESIVO").required(),necesidadLiquidez:Joi.string().valid("ALTA","MEDIA","BAJA").required(),objetivoPrincipal:Joi.string().valid("PRESERVAR","CRECER","INGRESO","META_ESPECIFICA").required()});
router.put("/perfil-inversion",validate(perfilInv),async(req,res)=>res.json({ok:true,perfil:await service.upsertPerfilInversion(req.personalAuth.userId,req.validated)}));
router.get("/patrimonio",async(req,res)=>res.json({ok:true,patrimonio:await service.patrimonio(req.personalAuth.userId)}));
router.get("/plan-financiero",async(req,res)=>res.json({ok:true,plan:await service.planFinanciero(req.personalAuth.userId)}));
const credito=Joi.object({nombre:Joi.string().max(100).required(),saldo:Joi.number().min(0).required(),tasaMensualPct:Joi.number().min(0).max(100).required(),cuotaMensual:Joi.number().min(0).required(),mesesRestantes:Joi.number().integer().min(0).max(600).required()});
router.post("/creditos",validate(credito),async(req,res)=>res.status(201).json({ok:true,credito:await service.registrarCredito(req.personalAuth.userId,req.validated)}));
const meta=Joi.object({nombre:Joi.string().max(120).required(),objetivo:Joi.number().positive().required(),acumulado:Joi.number().min(0).default(0),fechaObjetivo:Joi.date().iso().allow(null)});
router.post("/metas",validate(meta),async(req,res)=>res.status(201).json({ok:true,meta:await service.crearMeta(req.personalAuth.userId,req.validated)}));
router.get("/resumen",async(req,res)=>res.json({ok:true,resumen:await service.resumen(req.personalAuth.userId)}));router.get("/analisis",async(req,res)=>res.json({ok:true,analisis:await brain.analizar(req.personalAuth.userId)}));
const simulacion=Joi.object({capital:Joi.number().positive().required(),tasaMensualPct:Joi.number().min(0).max(100).required(),meses:Joi.number().integer().min(1).max(600).required()});
router.post("/creditos/simular",validate(simulacion),(req,res)=>res.json({ok:true,simulacion:service.simularCredito(req.validated)}));
router.post("/creditos/evaluar",validate(simulacion),async(req,res)=>res.json({ok:true,evaluacion:await service.evaluarCredito(req.personalAuth.userId,req.validated)}));
module.exports=router;