"use strict";
require("dotenv").config();
const http=require("http");const path=require("path");const express=require("express");const mongoose=require("mongoose");const {Server}=require("socket.io");const routes=require("./routes");const {registerPersonalRealtime}=require("./realtime/personalRealtime");const sync=require("./security/entitlementSync.service");
const REQUIRED=["PERSONAL_MONGO_URI","PERSONAL_JWT_SECRET","PERSONAL_RESET_SECRET","PERSONAL_IDEMPOTENCY_SECRET","PERSONAL_DATA_KEY","PERSONAL_ENTITLEMENT_SYNC_SECRET"];
function validateEnv(){const missing=REQUIRED.filter(k=>!process.env[k]);if(missing.length)throw new Error("Configuración personal incompleta: "+missing.join(","));const key=Buffer.from(process.env.PERSONAL_DATA_KEY,"base64");if(key.length!==32)throw new Error("PERSONAL_DATA_KEY debe ser base64 de 32 bytes");}
function buildApp(){const app=express();app.disable("x-powered-by");app.set("trust proxy",1);app.use(express.json({limit:"256kb",strict:true}));app.use(express.urlencoded({extended:false,limit:"64kb",parameterLimit:100}));app.post("/internal/entitlements/sync",async(req,res)=>{try{if(!sync.verify(req.body,req.get("x-gruk-signature")))return res.status(401).json({ok:false,error:"Firma inválida"});return res.json(await sync.apply(req.body));}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"Error de sincronización"});}});app.get("/healthz",(_req,res)=>res.status(mongoose.connection.readyState===1?200:503).json({ok:mongoose.connection.readyState===1,service:"gruk-finanzas-personales"}));app.use("/api",routes);app.use(express.static(path.join(__dirname,"../../public"),{index:false}));app.get("/",(_req,res)=>res.sendFile(path.join(__dirname,"../../public/finanzas-personales.html")));return app;}
async function start(){validateEnv();const app=buildApp(),server=http.createServer(app),io=new Server(server,{maxHttpBufferSize:256000,cors:{origin:false}});registerPersonalRealtime(io);await mongoose.connect(process.env.PERSONAL_MONGO_URI,process.env.PERSONAL_MONGO_DB?{dbName:process.env.PERSONAL_MONGO_DB}:{ });const port=Number(process.env.PERSONAL_PORT||3100);await new Promise((resolve,reject)=>{server.once("error",reject);server.listen(port,"0.0.0.0",resolve);});console.log("GRUK Finanzas Personales escuchando en",port);return{app,server,io};}
if(require.main===module)start().catch(err=>{console.error("[FIN_PERSONAL_BOOT]",err.message);process.exit(1);});
module.exports={buildApp,start,validateEnv};
