"use strict";
require("dotenv").config();
const http=require("http");const path=require("path");const express=require("express");const mongoose=require("mongoose");const {Server}=require("socket.io");const routes=require("./routes");const {registerPersonalRealtime}=require("./realtime/personalRealtime");const sync=require("./security/entitlementSync.service");const crypto=require("crypto");const MarketSnapshot=require("./models/marketSnapshot.model");const marketValidator=require("./services/marketDataValidator.service");const macroCollector=require("./services/macroCollector.service");
const REQUIRED=["PERSONAL_MARKET_INGEST_SECRET","PERSONAL_MONGO_URI","PERSONAL_JWT_SECRET","PERSONAL_RESET_SECRET","PERSONAL_IDEMPOTENCY_SECRET","PERSONAL_DATA_KEY","PERSONAL_ENTITLEMENT_SYNC_SECRET"];
function validateEnv(){const missing=REQUIRED.filter(k=>!process.env[k]);if(missing.length)throw new Error("Configuración personal incompleta: "+missing.join(","));const key=Buffer.from(process.env.PERSONAL_DATA_KEY,"base64");if(key.length!==32)throw new Error("PERSONAL_DATA_KEY debe ser base64 de 32 bytes");}
function buildApp(){const app=express();app.disable("x-powered-by");app.set("trust proxy",1);app.use(express.json({limit:"256kb",strict:true}));app.use(express.urlencoded({extended:false,limit:"64kb",parameterLimit:100}));app.post("/internal/market/snapshots",async(req,res)=>{try{const raw=JSON.stringify(req.body),sig=String(req.get("x-gruk-signature")||""),expected=crypto.createHmac("sha256",process.env.PERSONAL_MARKET_INGEST_SECRET).update(raw).digest("hex");if(sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return res.status(401).json({ok:false,error:"Firma inválida"});const rows=Array.isArray(req.body)?req.body:[req.body];if(!rows.length||rows.length>100)return res.status(400).json({ok:false,error:"Lote inválido"});for(const x of rows){try{marketValidator.validateSnapshot(x)}catch(v){return res.status(400).json({ok:false,error:v.message})}if(!x.riesgo)return res.status(400).json({ok:false,error:"Snapshot sin clasificación de riesgo"});}await MarketSnapshot.insertMany(rows,{ordered:true});return res.status(201).json({ok:true,insertados:rows.length});}catch(e){return res.status(e?.code===11000?409:500).json({ok:false,error:e?.code===11000?"Snapshot duplicado":"Error de ingestión"});}});app.post("/internal/entitlements/sync",async(req,res)=>{try{if(!sync.verify(req.body,req.get("x-gruk-signature")))return res.status(401).json({ok:false,error:"Firma inválida"});return res.json(await sync.apply(req.body));}catch(e){return res.status(e.statusCode||500).json({ok:false,error:e.statusCode?e.message:"Error de sincronización"});}});app.get("/healthz",(_req,res)=>res.status(mongoose.connection.readyState===1?200:503).json({ok:mongoose.connection.readyState===1,service:"gruk-finanzas-personales"}));app.use("/api",routes);app.use("/api",(err,_req,res,_next)=>{console.error("[FIN_PERSONAL_API]",err.message);return res.status(err.statusCode||500).json({ok:false,error:err.statusCode?err.message:"Error interno"});});app.use(express.static(path.join(__dirname,"../../public"),{index:false}));app.get("/",(_req,res)=>res.sendFile(path.join(__dirname,"../../public/finanzas-personales.html")));return app;}
async function start(){validateEnv();const app=buildApp(),server=http.createServer(app),io=new Server(server,{maxHttpBufferSize:256000,cors:{origin:false}});registerPersonalRealtime(io);await mongoose.connect(process.env.PERSONAL_MONGO_URI,process.env.PERSONAL_MONGO_DB?{dbName:process.env.PERSONAL_MONGO_DB}:{ });const port=Number(process.env.PORT||process.env.PERSONAL_PORT||3100);if(!Number.isInteger(port)||port<1||port>65535)throw new Error("Puerto personal inválido");await new Promise((resolve,reject)=>{server.once("error",reject);server.listen(port,"0.0.0.0",resolve);});console.log("GRUK Finanzas Personales escuchando en",port);try{await macroCollector.persistColombia();console.log("GRUK macro CO actualizado");}catch(e){console.error("[MACRO_COLLECTOR]",e.message)}return{app,server,io};}
if(require.main===module)start().catch(err=>{console.error("[FIN_PERSONAL_BOOT]",err.message);process.exit(1);});
module.exports={buildApp,start,validateEnv};
